spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finled
    username: postgres
    password: 123456ds

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    show-sql: true