spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finled}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    show-sql: true